### ISSUE TITLE
Map value() and set() functions can trip observation during instantiation

### ISSUE THREAD

**Issue by dylanrtt** [canjs/canjs#2528] opened 2016-09-28 00:13 UTC
Instantiating a map instance within a compute can add unwanted dependencies to the compute by way of `value()` and `set()` functions that perform reads. In the following example, the `offset` setter reads `count` during the map's instantiation, which becomes a dependency of the outer compute, so changing `count` later on reruns the compute.

I see this behavior as undesirable in this instance, though perhaps there are cases where you would actually want the compute to rerun.

``` js
var PaginateVM = can.Map.extend({
  define: {
    offset: {
      value: 1,
      set: function(newVal) {
        var count = this.attr('count');
        return (newVal > count) ? count : newVal;
      }
    }
  }
});

var compute = can.compute(function() {
  console.log('getting compute');
  return new PaginateVM();
});

compute.bind('change', function(ev, newVal, oldVal) {
  console.log('compute changed');
});

var paginate = compute();

// reruns compute
paginate.attr('count', 10);
```

http://jsbin.com/rowoziqeyu/edit?js,console

**Comment by justinbmeyer** [comment] 2016-09-28 01:42
Thanks for reporting.  I think this is a duplicate of another issue.  I thought `setters` were `Observation.ignore`-ed so whatever they read can't be watched by a compute.  But it seems like that's not the case.

In general, anything involved with setting state shouldn't be observable.  However, it's hard to differentiate a read that is part of setting state, and a read for deriving state.

For 3.0, we could make any constructor and setter `Observation.ignore`-ed by default. Also, we can make `Observation.ignore` public so it's easier to spell out these cases:


```js
var compute = can.compute(function() {
  console.log('getting compute');
  return Observation.ignore(function(){
    return new PaginateVM();
  })();
});
```

Thoughts?

**Comment by dylanrtt** [comment] 2016-09-28 02:59
You might be thinking of [#2220](https://github.com/canjs/canjs/issues/2220) which also has to do with instantiating maps in computes.

I think wrapping `value()` and `set()` functions in `Observation.ignore` or something similar is a good idea.

A public `Observation.ignore` would be nice to have. I have avoided using `can.__notObserve` in the past because it is private.

**Comment by justinbmeyer** [comment] 2017-04-12 01:49
Issue moved to [canjs/can-map-define #32](https://github.com/canjs/can-map-define/issues/32) via [**ZenHub**](https://www.zenhub.com/)

**Closed by justinbmeyer** 2017-04-12 01:49 UTC
