### ISSUE TITLE
Stache will not bind to %key when rendering value inside #each

### ISSUE THREAD

**Issue by akagomez** [canjs/canjs#2385] opened 2016-05-03 17:48 UTC
Given a map like this: 

```
var map = new can.Map({
  0: true,
  1: false,
  2: true
});
```

I want to render and update the values of each key in the map like this: 

```
<ul>    
  {{#each map}}
    <li>
      <input type="checkbox" {($checked)}="map.{{%key}}" />
      {{%key}}: {{.}}
    </li>
  {{/each}}
</ul>
```

Unfortunately it appears the template will not bind to `%key` on `map` using `{{.}}`: http://jsbin.com/hojetiq/5/edit?html,js,console,output

**Comment by dylanrtt** [comment] 2016-05-03 19:19
I think this is related to (or a duplicate of) #2318.

**Comment by justinbmeyer** [comment] 2016-09-02 14:33
Closing for: #2318

**Closed by justinbmeyer** 2016-09-02 14:33 UTC
