### ISSUE TITLE
Ability to use map.define on all Map classes in inheritance chain

### ISSUE THREAD

**Issue by isadovskiy** [canjs/canjs#1322] opened 2014-11-10 15:14 UTC
At the moment it's not possible to use map.define plugin to define properties both on parent and child Map instances. Define config in child class completely overrides parent's "define" section. It should extend instead.

Please check the example: http://jsfiddle.net/njuw9sss/1/

**Comment by isadovskiy** [comment] 2015-08-26 21:50
Any update on this issue?

Or there is a workaround, which allows to create MapA -> MapB -> can.Map inheritance chain and define properties both on MapA and MapB level?

**Comment by justinbmeyer** [comment] 2015-08-26 22:21
For my notes, the issue is when the inheriting constructor has a define property like:

```
var ParentModel = can.Map.extend({
    define: {
        rawProp: {
            type: '*',
            value: {}
        }
    }
});

var ChildModel = ParentModel.extend({
    define: {
         //   
    }
});
``

**Comment by justinbmeyer** [comment] 2015-08-26 22:36
@isadovskiy There's been no progress on this, but it's probably an easy fix.  First, you need access to the `base` can.Map in Map.setup: https://github.com/bitovi/canjs/blob/minor/map/map.js#L29.  It's the first argument so make that line something like:

```
setup: function (baseMap) {
```

Then, you need to copy everything in `baseMap.prototype.define` to a new object and then everything in `this.prototype.define` to that object.  Finally, set that object to `this.prototype.define`.  Something like the following might work:

```js
if(baseMap.prototype.define) {
  var defines = can.simpleExtend({}, baseMap.prototype.define)
  can.simpleExtend(defines, this.prototype.define);
  this.prototype.define = defines;
}
```

Now this will only copy properties, but not allow you to overwrite specific values within a property. For example, the following wouldn't work as someone might expect:

```js
var ParentModel = can.Map.extend({
    define: {
        rawProp: {
            type: 'number',
            value: 7
        }
    }
});

var ChildModel = ParentModel.extend({
    define: {
         rawProp: {
           value: 8
         }   
    }
});
```

For that to work, you need to recursively copy all properties over.  You might be able to use `can.extend(true, dest, source)`, but I think that might have unexpected results.  

Better would be to only copy values two levels deep.  Maybe create a small helper function at the bottom of `can/map/map.js` like:

```js
var twoLevelDeepExtend = function(d, s){
  for(var prop in s) {
     d[prop] = d[prop] || {};
     can.simpleExtend(d[prop] , s[prop])
  }
};
```

And then:


```js
if(baseMap.prototype.define) {
  var defines = twoLevelDeepExtend({}, baseMap.prototype.define)
  twoLevelDeepExtend(defines, this.prototype.define);
  this.prototype.define = defines;
}
```

hit me up on gitter if you want to work on it.

**Comment by justinbmeyer** [comment] 2016-05-19 22:47
Closing for https://github.com/canjs/can-map-define/issues/2 and https://github.com/canjs/can-define/issues/18.  Hopefully @chasenlehara can make this work over there.

**Closed by justinbmeyer** 2016-05-19 22:47 UTC
Labels: Bug, Solved on paper

**Comment by chasenlehara** [comment] 2016-05-20 18:53
@justinbmeyer I have some other open source stuff I want to work on, so if someone takes those before I get a chance, they can use my PR: https://github.com/canjs/canjs/pull/2222
