### ISSUE TITLE
Broken URLs on generated website

### ISSUE THREAD

**Issue by leoj3n** [canjs/canjs#3128] opened 2017-03-25 05:06 UTC
Visit:

http://canjs.com/doc/can-define/map/map.html

Clicking "Edit on GitHub" results in 404.

**Comment by chasenlehara** [comment] 2017-03-27 18:17
Dupe of https://github.com/canjs/bit-docs-html-canjs/issues/204

**Closed by chasenlehara** 2017-03-27 18:17 UTC
