### ISSUE TITLE
null and undefined should bypass `Type` conversion in can-map-define and can-define ~5

### ISSUE THREAD

**Issue by gsmeets** [canjs/canjs#2316] opened 2016-03-08 08:46 UTC
Did the behaviour of null values change down the line somewhere? (2.1 to 2.2 maybe?)

When my server returns a null value and I have a Type setter defined an object is instantiated. I recall this not being the case in the past. What's the idea behind this? With a .NET backend it's not really feasible to switch between completely ignoring a property and outputting a null value at random.

using canjs 2.2.9

**Comment by Bajix** [comment] 2016-03-09 19:15
I have noticed this as well, and I did appreciate using null as a placeholder back in the day. @justinbmeyer thoughts on letting null bypass type conversion?

You have a couple of options here. The `type` converter gives you more fine grain control, as you can pass in a function and do your `Type` conversion there. 

The best solution for you *at the moment* is to use parseModels to clean up your data. This is a good place to do the respective can.Model.model calls as well, as otherwise nested data is merged, and it creates [headaches](https://github.com/canjs/canjs/issues/1647). It's not adequate to manually hookup can.Model.model within the `type` setter, nor is can.Model.model compatible with `Type`.

**Comment by justinbmeyer** [comment] 2016-09-01 19:48
null should bypass type conversion.

**Comment by justinbmeyer** [comment] 2016-09-01 19:56
Problem is here in can-map-define: https://github.com/canjs/can-map-define/blob/master/can-map-define.js#L275

And here in in can-define: https://github.com/canjs/can-define/blob/master/can-define.js#L352


Please solve this in both repos.

**Comment by bmomberger-bitovi** [comment] 2016-09-09 19:41
Working on these issues now for can-map-define and can-define, but with my thoughts I posted in https://github.com/canjs/can-map-define/issues/8 there still may be some cases in which default behaviors aren't desired.

These are the breakdown of type cases after fixing:

- '*' and 'compute' are essentially non-events; these just store and return what is passed in.

- 'number', 'string', and 'date' were already functioning as intended here.  `null` and `undefined` retain their values.

- 'htmlbool' has to be an exception because it's really the presence/absence of a string value that determines true and false.  In other words, `null` *should be* false here.

- 'boolean' is less clear.  I think it should be consistent with the other basic types above but it's currently not: nulls become `false`.

- `Type` constructors are the heart of the issue here, since they should be nullable by default and weren't nullable at all; you would have to `.removeAttr()` on their respective properties.  This I am fixing.

So the real judgment calls here are twofold:

1. Should we null out regular booleans if null is passed in?

2. Should we allow the user to override these behaviors with the addition of a `nullable` property?

**Comment by BigAB** [comment] 2016-09-09 19:54
It seems to be, if the type is set to `boolean` then the consumer will use it that way, so I think `null` converting to `false` would be fine.

It seems to me like seting the property/attribute to `null` would be the "right" behaviour if you set an object value as null, so I, personally do not see a use case for the `nullable` property

**Closed** 2016-10-17 21:19 UTC
Labels: Bug, P1, review
