### ISSUE TITLE
Change data binding does not work for list of primitives

### ISSUE THREAD

**Issue by isadovskiy** [canjs/canjs#1692] opened 2015-05-13 17:25 UTC
Please check the example: http://jsfiddle.net/cs725u9e/2/

There is a can.List  of strings, which is bound to view. Adding new items into lists reflects on UI immediately. However changing item in the list does not update the UI (click "Change" button to reproduce).

CanJS version is 2.2.5

**Comment by daffl** [comment] 2015-05-13 17:45
Do you know if this is a regression in 2.2.x?

**Comment by isadovskiy** [comment] 2015-05-13 17:46
I can try with 2.1.4

**Comment by isadovskiy** [comment] 2015-05-13 17:50
Looks like the issue existed at least since 2.1.4: http://jsfiddle.net/cs725u9e/3/

So it's not 2.2 regression issue.

**Comment by justinbmeyer** [comment] 2015-05-14 20:15
This has probably existed forever because `can.view.live.list` only listens to add/remove events.

I'm not sure what the right fix should be.  Possibly we should trigger an `remove` and `add` event whenever an index is updated in this way.

**Comment by justinbmeyer** [comment] 2015-05-18 19:19
Btw, this should work w/o `{{#each list}}` and just using `{{#list}}` instead

**Comment by isadovskiy** [comment] 2015-05-18 21:19
@justinbmeyer, as I remember, you explained at some point, {{#list}} re-renders the whole list, while {{#each list}} re-renders just necessary elements. Isn't the case anymore?

**Comment by justinbmeyer** [comment] 2015-05-18 21:55
This is still the case.

**Comment by justinbmeyer** [comment] 2015-12-10 19:45
The solution is that when #each is creating a context, it should pass:

- the property name that was used to get the context (as a compute in case the property name changes (ex: `0` to `1`))
- the object who's property the context is (basically if I get the context by doing `foo.bar` ... this is `foo`).

Then, when reading a property like `.` or `this`, a compute should be given instead of the context.

**Comment by justinbmeyer** [comment] 2016-05-22 21:36
Closing for: https://github.com/canjs/can-stache-bindings/issues/8

**Closed by justinbmeyer** 2016-05-22 21:36 UTC
Labels: Bug
