### ISSUE TITLE
all readme links broken

### ISSUE THREAD

**Issue by aretecode** [canjs/canjs#3449] opened 2017-07-25 09:59 UTC
https://github.com/canjs/canjs#core-collection

all go to broken links

**Comment by cherifGsoul** [comment] 2017-07-25 14:30
this because of the trainling slash in the markdown links.

**Comment by phillipskevin** [comment] 2017-07-25 15:00
I think this is a duplicate of https://github.com/canjs/canjs/issues/2737.

**Closed by phillipskevin** 2017-07-25 15:00 UTC
