### ISSUE TITLE
can@3.8.2 -> 3.9.0 breaks the simple weather recipe

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#3541] opened 2017-09-07 17:27 UTC
https://jsbin.com/xojinezewu/edit?html,js,output

Change 3.8.2 to 3.9.0 and it breaks.  All versions >= 3.9.0 break.

To break the app, type Chicago and try to "pick your place".  Nothing happens.

**Comment by justinbmeyer** [comment] 2017-09-07 17:33
Here's a simplified version: https://jsbin.com/xojinezewu/edit?html,js,output

**Comment by phillipskevin** [comment] 2017-09-08 02:04
@justinbmeyer The issue is that synchronous getters are now set up as [Observations](https://github.com/canjs/can-define/blob/af174485b386b70382d35ed4b768333022e89628/can-define.js#L341). So, when the value is set, `Observation.prototype.update` is called [here](https://github.com/canjs/can-define/blob/af174485b386b70382d35ed4b768333022e89628/can-define.js#L66), but the `ScopeKeyData` that depends on this `Observation` is never updated. I put in a potential fix for this here: https://github.com/canjs/can-define/pull/261.

Let me know if you think there is a better way to fix this.

**Comment by justinbmeyer** [comment] 2017-09-08 03:54
Why is `ScopeKeyData` never updated? Why was it previously?

**Comment by phillipskevin** [comment] 2017-09-08 13:37
I'm not sure why `ScopeKeyData` is never updated - it seems that the `boundGet` function needs to observe `computeObj.valueTrap.lastSetValue`, but it is not observable.

It was working previously because getters were always set up as [computes](https://github.com/canjs/can-define/commit/1707547836de343615784c6f87973b03712e9d52#diff-af305ad7545904dbf5a494ed400024d3L272) (although there was no `ScopeKeyData` at that time).

**Comment by phillipskevin** [comment] 2017-09-08 20:11
canjs 3.10.2 is out and resolves this issue.

**Closed by phillipskevin** 2017-09-08 20:11 UTC
Labels: bug
