### ISSUE TITLE
2-way binding out of sync when parent coerces a value set by the child

### ISSUE THREAD

**Issue by dylanrtt** [canjs/canjs#2677] opened 2016-11-02 21:01 UTC
While using a 2-way stache binding with the new syntax, if the child sets a value on the parent which it immediately coerces through set/get, the child is not updated with the new value.

Example:

```html
<input {($value)}="foo">
```

```js
foo: {
  type: 'number',
  set(newVal) {
    return newVal > 5 ? 5 : newVal;
  }
}
```

If the user enters a value greater than `5`, the parent's `foo` property is set to 5, but the input still shows whatever was entered.

http://jsbin.com/zehugoxaxa/edit?html,js,console,output

This problem does not occur with `can-value`, so it's a viable workaround for `{($value)}`.

This may also affect 2-way bindings between components, but I have not checked.

**Comment by justinbmeyer** [comment] 2017-04-12 01:58
I thought this is fixed in 3.0, but this is a duplicate of: https://github.com/canjs/can-stache-bindings/issues/162

**Closed by justinbmeyer** 2017-04-12 01:58 UTC
