### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by sszabolcs** [canjs/canjs#3147] opened 2017-04-04 14:17 UTC
Hi!

I think I've found a memory leak.
[JS Bin](http://jsbin.com/haqaley/edit?html,js,console,output)

To reproduce the leak:
1. Take a heap snapshot
2. Click on Insert
3. Click on Remove
4. Take a heap snapshot
5. Click on Insert
6. Click on Remove
7. Take a heap snapshot

Now view the list of objects created between the first and the second snapshot. You'll see that there are items which cannot be garbage collected:
![image](https://cloud.githubusercontent.com/assets/18262711/24660836/f219d102-1950-11e7-8f0d-fa3f9bad6359.png)

When I discovered the issue I was using Chrome 56.... I don't know the exact version because when I tried to check my Chrome version it started to update to 57.0.2987.133. I had no choice it upgraded to the latest stable version. The problem still exists with Chrome 57.0.2987.133.

In the JS Bin I use a custom build. Here are the versions for the modules I use in the custom build:
can-component: 3.0.7
can-route: 3.0.8
can-stache: 3.0.21
can-stache-bindings: 3.0.13
can-stache-converters: 3.0.7
can-compute: 3.0.7
can-event: 3.2.0
can-view-model: 3.1.3
can-connect/can/base-map/base-map: 1.3.8
can-define/map/map: 1.0.17
can-define/list/list: 1.0.17
can-set: 1.1.0
can-fixture: 1.0.13
can-map: 3.0.6
can-list: 3.0.3
can-map-backup: 3.0.3
can-map-define: 3.0.6
can-connect/can/model/model: 1.3.8
can-jquery: 3.0.6

Thanks!

**Comment by justinbmeyer** [comment] 2017-04-04 17:04
RequestInstances tracks which Ajax requests have been made. Have all Ajax requests in your app completed successfully? (On phone so haven't looked at jsbin)

**Comment by sszabolcs** [comment] 2017-04-04 20:30
Yes, all Ajax requests end with status 200. In the example - JS Bin - the request is handled with a fixture and it ends with success, too.

**Comment by sszabolcs** [comment] 2017-04-04 20:42
Here I include another version of this code, where I'm using can.Model. The problem looks alike. Maybe it can help hunting down the root cause: [JS Bin](http://jsbin.com/zikubu/3/edit?html,js,console,output)

And here is a screenshot for the leak with this version of code: ![image](https://files.gitter.im/canjs/canjs/r3NK/blob)

**Comment by sszabolcs** [comment] 2017-04-10 07:47
@justinbmeyer Hi! Did you make some progress in resolving this issue?

**Comment by justinbmeyer** [comment] 2017-04-10 14:18
I haven't. I was on vacation all last week. I get back tomorrow.

**Comment by sszabolcs** [comment] 2017-04-10 14:56
Ok, thanks for the info.

**Comment by phillipskevin** [comment] 2017-04-18 14:19
@sszabolcs This issue is fixed in [can-util v3.3.7](https://github.com/canjs/can-util/releases/tag/v3.3.7). Thanks again for reporting it!

**Comment by sszabolcs** [comment] 2017-04-18 14:52
@phillipskevin Thanks a lot! I'll test it!

**Comment by sszabolcs** [comment] 2017-04-20 12:42
@phillipskevin I've tested the fix. I don't know how but it seems to me that the leak is still there.
Here I have a test code:
[playcode.io](https://playcode.io/canjs3_define_map_list_binding/v1?tabs=console&app.html&script.js&output)
This time I used playcode.io because there is possible to include multiple in-the-place-edited js files and so I can have a custom CanJS build included and edited very easily and quickly. The custom CanJS build is an up-to-date CanJS 3.5.1 build. I've updated all the can* packages to the latest stable version so I have no outdated npm can package, but the leak is still there:
![image](https://cloud.githubusercontent.com/assets/18262711/25231218/57897244-25d7-11e7-9734-25e091271669.png)

Could you please check it? Thanks!

**Comment by phillipskevin** [comment] 2017-04-20 20:43
@sszabolcs if you don't use jquery for adding/removing the element, then your memory leak goes away. I'll take a look at why jquery causes a problem.

**Comment by sszabolcs** [comment] 2017-04-21 06:41
@phillipskevin Ok, thanks!

**Comment by phillipskevin** [comment] 2017-04-27 01:59
@sszabolcs [can-jquery@3.0.7](https://github.com/canjs/can-jquery/releases/tag/v3.0.7) is released with fixes for these memory leaks when using jQuery. Please let us know if you're still seeing issues after upgrading to this version.

**Closed by phillipskevin** 2017-04-27 01:59 UTC

**Comment by sszabolcs** [comment] 2017-04-27 13:49
@phillipskevin Thank you for your work! The leak has gone in the playcode example.
When I merged the updated CanJS libs in to our app I sadly realized that there is another leak...
I've successfully narrowed down the cause of the problem.
Here is an example: [playcode.io](https://playcode.io/canjs3_define_map_list_binding/v3?tabs=console&app.html&script.js&output)
If I remove the following snippet from the app.html in the 11th row:
```
{{#if data}}data-filter="{{data}}"{{/if}}
```
the leak disappears.

Do you have any idea what's wrong with this?
Thanks!

**Comment by phillipskevin** [comment] 2017-04-27 14:40
I've opened https://github.com/canjs/can-jquery/issues/72 for that. Should be able to fix it today.

**Comment by phillipskevin** [comment] 2017-04-27 21:05
@sszabolcs [can-view-live@3.0.7](https://github.com/canjs/can-view-live/releases/tag/v3.0.7) is out with another fix.

**Comment by sszabolcs** [comment] 2017-04-28 11:54
@phillipskevin Thank you! The fix is correct **this** leak has disappeared.

I know you hate me but I've found another one... :cry:
[Here](https://playcode.io/canjs3_editor_component?tabs=console&app.html&script.js&output) I made an example for you. Reproduction steps are the same as in the earlier samples. Click on "Create new foo" then on "Cancel" and create snapshots:
![image](https://cloud.githubusercontent.com/assets/18262711/25527663/10656fbe-2c1a-11e7-83e3-92cc1b0aa339.png)

**Comment by phillipskevin** [comment] 2017-04-28 15:24
@sszabolcs I definitely appreciate the work you're doing to find these and help make CanJS better. I'll look into this issue today.

**Comment by sszabolcs** [comment] 2017-05-09 07:55
@phillipskevin Did you have time to work on this? Thanks!

**Comment by phillipskevin** [comment] 2017-05-09 14:26
@sszabolcs sorry, this got delayed while we were working to get CanJS 3.6.0 out. I will look into this today.

**Comment by phillipskevin** [comment] 2017-05-15 16:03
@sszabolcs are you still seeing this issue? I can't reproduce it with your code and the latest `can-*` versions.

**Comment by sszabolcs** [comment] 2017-05-16 11:06
@phillipskevin I'm still seeing it. I did the following steps:
1. installed a new can@3.8.1 package
2. built a custom CanJS js file based on this legacy.js:
```
var can = require('can-util/namespace');
    require('can-component');
    require('can-route');
    require('can-stache');
    require('can-stache-bindings');
    require('can-stache-converters');
    require('can-compute');
    require('can-event');
    require('can-view-model');
    require('can-connect/can/map/map');
    require('can-define/map/map');
    require('can-define/list/list');
    require('can-fixture');
    require('can-map');
    require('can-list');
    require('can-map-backup');
    require('can-map-define');
    require('can-connect/can/model/model');
    require('can-jquery');
    can.view.attr = can.view.callbacks.attr;
    can.view.tag = can.view.callbacks.tag;
    module.exports = can;
```
3. created a [2nd version of the sample code](https://playcode.io/canjs3_editor_component/v2?tabs=console&app.html&script.js&output) with the freshly built can.custom.js
4. took a heap snapshot
5. clicked 'Create new foo', then 'Cancel'
6. took a heap snapshot
7. clicked 'Create new foo', then 'Cancel'
8. took a heap snapshot
9. analyzed 'Objects allocated between Snapshot 1 and Snapshot 2'
10. found for example three HTMLOptionElement which were not garbage collected:
![image](https://cloud.githubusercontent.com/assets/18262711/26103088/2d696490-3a38-11e7-90a3-0b5f45401ff4.png)

What do you think?

**Comment by sszabolcs** [comment] 2017-05-16 11:38
And [here is a JSBin](http://jsbin.com/wavidor/edit?html,js,output) with the same code in case playcode.io would do anything nasty.

**Comment by sszabolcs** [comment] 2017-05-16 11:58
@phillipskevin I think we are a little bit closer: I've created a [new version](https://playcode.io/canjs3_editor_component_with_define_map?tabs=console&app.html&script.js&output) of the sample where the only modification in JS is that I use can.DefineMap for the FooEditorComponentVM instead of can.Map and there is NO LEAK! So the problem is somewhere in can.Map.

**Comment by phillipskevin** [comment] 2017-05-16 13:22
Yeah, I can reproduce with your can.custom.js, but not with these individual imports:

![image](https://cloud.githubusercontent.com/assets/5851984/26107986/c109cbcc-3a10-11e7-8d0d-dfe71534099e.png)

**Comment by phillipskevin** [comment] 2017-05-16 15:46
@sszabolcs I opened https://github.com/canjs/can-stache-bindings/issues/210 for this. We can discuss any further findings there.
