### ISSUE TITLE
routeUrl in templates doesn't seem to work with can.route.bindings.pushstate.root

### ISSUE THREAD

**Issue by pmtarantino** [canjs/canjs#2345] opened 2016-03-30 15:10 UTC
Hi, I am doing my first app in canjs and I found an error I couldn't solve. The app was working fine with urls and templates, but I need to use pushstate to start using urls like /first/second.

I have my app inside a directory, so it is localhost/app/. Just calling the pushstate plugin made that my links started to pointing from localhost/app/#!page to localhost/page, which "worked" (the bindings worked, etc), but it doesn't look fine.

So I added the line:
`can.route.bindings.pushstate.root = "/app/"`
in my app.js, however, the links on my template that I created using routeUrl(page="page1"), started to point to localhost/?page=page1, and of course, this breaks the app.

I thought I was mis-configuring the root, but testing generating the urls in the browser console I get the expected results:

```
can.route.url({page: "testing"});
"/app/testing"
```

Am I doing something wrong? Or this is an error in canjs?

Thank you!

**Comment by justinbmeyer** [comment] 2016-09-02 14:51
@pmtarantino I'm not sure what's happening.  Are your templates being called before your routing rules are defined?

For example, something like:

```
var frag = template({ ... })
document.body.appendChild(frag)

can.route(":page")
can.route.ready()
```

If this is the case, it's possible they don't know about the routing rules to write out the correct links.

**Comment by justinbmeyer** [comment] 2017-04-12 01:11
@pmtarantino I'm closing this issue.  I'll re-open if you can give me a little more information.  Thanks!

**Closed by justinbmeyer** 2017-04-12 01:11 UTC

**Comment by Hamelina** [comment] 2018-06-20 13:57
Hi there, 
I have quite the same issue here : I am trying to use routeUrl like this : href="{{routeUrl page='chat'}}  on a button. But the problem is that I get the following warning : ChatAppView:8: Unable to find helper "routeUrl".

**Comment by chasenlehara** [comment] 2018-06-20 17:33
@Hamelina This sounds like a different problem; would you mind opening a new issue with more info? What version of CanJS? Are you importing [can-stache/helpers/route](https://v3.canjs.com/doc/can-stache/helpers/route.html) or [can-stache-route-helpers](https://canjs.com/doc/can-stache-route-helpers.html) somewhere in your app or template?
