### ISSUE TITLE
infinite loop on can.Map docs

### ISSUE THREAD

**Issue by tyuwan** [canjs/canjs#2266] opened 2016-02-13 03:42 UTC
Please fix this page. I'm unable to look at the documentation.
[https://canjs.com/docs/can.Map.prototype.define.html](https://canjs.com/docs/can.Map.prototype.define.html)

**Comment by justinbmeyer** [comment] 2016-02-13 03:59
Duplicate of #2255

**Closed** 2016-02-13 04:00 UTC
