### ISSUE TITLE
Stache removes attribute "id"  from input elements if value should be interpolated

### ISSUE THREAD

**Issue by rangermeier** [canjs/canjs#2110] opened 2015-12-01 15:20 UTC
An template like `<input id="{{ id }}" value="{{ value}}">` is rendered like `<input value="abc">`. Note how the *id*-attribute is omitted. This happens for all kinds of form elements: input, select, textarea,..

http://jsbin.com/zobamum/edit?html,css,js,output

**Comment by dylanrtt** [comment] 2015-12-01 22:24
Looks like a 2.3.3 regression. It works in 2.3.2:

http://jsbin.com/rilinopufi/edit?html,js,output

**Comment by justinbmeyer** [comment] 2015-12-02 03:32
#2108 solves this.  Closing as duplicate.

**Closed by justinbmeyer** 2015-12-02 03:32 UTC
Labels: Bug
