### ISSUE TITLE
sort plugin forces comparing 'comparator' values, even when overriding the comparator function

### ISSUE THREAD

**Issue by gsmeets** [canjs/canjs#2159] opened 2016-01-02 21:31 UTC
I use a custom sort comparator function on a can.Map.List. In 2.3.x (I guess with the changes to the sort plugin) this breaks down. In 2.2.x it works.

When I remove the default comparator string on my model, the sorting works again. 
What's happening is that instead of the item itself, the value specified by the original comparator is used instead.

Culprits seem to be:
https://github.com/canjs/canjs/blob/master/list/sort/sort.js#L207-L209
and
https://github.com/canjs/canjs/blob/master/list/sort/sort.js#L251-252

I hope this behaviour isn't intentional.

**Comment by justinbmeyer** [comment] 2016-01-02 23:59
@gsmeets can you provide a breaking example?  I'm not sure exactly what you are describing.

**Comment by gsmeets** [comment] 2016-01-03 09:50
I'll create a PR with a breaking test.

**Comment by akagomez** [comment] 2016-02-10 19:46
I'm struggling to understand also. Some pseudo code would probably go a long way here.

**Comment by akagomez** [comment] 2016-02-11 15:23
Upon revisiting this issue, I'm starting to think the issue is that passing a comparator to the `.sort()` method directly isn't overriding the predefined comparator on the `can.List`. 

I'll put a test together to see if that's the case.

**Comment by akagomez** [comment] 2016-02-12 15:04
If I had to guess, I'd say that's the issue: http://jsbin.com/gicuji/embed?js,console

In the previous version of the sort plugin, did the comparator passed to `.sort(newComparator)` override the configured `.attr('comparator', oldComparator)`?

I'm not sure why we even handle this case at all. It's not documented. 

Anyway, here's what I think we should do: 

- Move the contents of `sort` to `_sort`
- When `.attr('comparator', value)` is set, call `_sort`
- Redirect `.sort(value)` calls to `.attr('comparator', value)` thus updating the comparator and re-sorting the collection

Afterwards any inserts will be made based on the last comparator set, which in the JSBin above would be the string passed to `.sort()`

Does that cover it @gsmeets?

**Comment by gsmeets** [comment] 2016-02-19 09:36
Sorry, been a bit busy. Right in the middle of crunch time. ;)

The problem is this:
http://jsbin.com/fonipulufa/1/edit?js,console,output

At the bottom I pass in a custom compare function, but because of the specified comparator instead of getting the maps as parameters to my sort function, I'm getting the prices.

**Comment by akagomez** [comment] 2016-02-22 14:46
Thanks for the clarification @gsmeets. I'll take a look at this as soon as I can.

**Comment by akagomez** [comment] 2016-03-02 02:16
This was speculated to be closed in #2257, but @gsmeets added more context after it was written. This is still an open issue.

**Closed** 2016-05-19 16:32 UTC
Labels: in progress
